### ISSUE TITLE
[TODO] Encrypted /boot

### ISSUE THREAD

**Issue by LeoMeinel** [LeoMeinel/mdadm-encrypted-btrfs#35]
https://wiki.archlinux.org/title/dm-crypt/Encrypting_an_entire_system#Encrypted_boot_partition_(GRUB)

https://wiki.archlinux.org/title/dm-crypt/Encrypting_an_entire_system#Btrfs_subvolumes_with_swap

> If using UEFI, an [EFI system partition](https://wiki.archlinux.org/title/EFI_system_partition) (ESP) is required. /boot itself may reside on / and be encrypted; however, the ESP itself cannot be encrypted. In this example layout, the ESP is /dev/sda1 and is mounted at /efi. /boot itself is located on the system partition, /dev/sda2.

The /boot partition should be a seperate partition in my opinion and /efi being unencrypted should be fine.

**Comment by LeoMeinel** [comment]
https://wiki.archlinux.org/title/GRUB#Encrypted_/boot

**Comment by LeoMeinel** [comment]
https://github.com/Szwendacz99/Arch-install-encrypted-btrfs

**Comment by LeoMeinel** [comment]
I might have to use the main partition for boot.

**Comment by LeoMeinel** [comment]
Add key to root partition that can unlock boot partitions!
That way the pacman hook won't be that annoying.

**Comment by LeoMeinel** [comment]
`partition-disks.sh` should be done.

# TODO

- [ ] `setup.sh`
- [ ] `post-install.sh`

**Comment by LeoMeinel** [comment]
Finally got through the install. Even tho I wasn't sure if what I was doing is correct, GRUB boots :) So I guess I can close this soon.

**Comment by LeoMeinel** [comment]
> Finally got through the install. Even tho I wasn't sure if what I was doing is correct, GRUB boots :) So I guess I can close this soon.

I guess I was too early :smile:
GRUB boots from the encrypted partition. However there is probably something wrong with the EFI partition since GRUB doesn't continue after the passphrase for /dev/md0 was entered.
Might be something else aswell.

**Comment by LeoMeinel** [comment]
![Image](https://gcdnb.pbrd.co/images/gFMIG3yVmHmT.png?o=1)

**Comment by LeoMeinel** [comment]
# TODO

- [ ] partition-disks.sh (Erasing after reboot)
- [ ] setup.sh (Make GRUB boot; [cryptboot](https://github.com/kmille/cryptboot))
- [ ] post-install.sh

**Comment by LeoMeinel** [comment]
Not having a seperate /boot might be better. I'll see if I can find a way to do that.

**Comment by LeoMeinel** [comment]
https://gist.github.com/huntrar/e42aee630bee3295b2c671d098c81268

https://gist.github.com/mattiaslundberg/8620837

https://gist.github.com/jirutka/a914c442f42f78a8a22847d57ba3900d

Might also be an option to not have /boot encrypted but signed with secure boot enabled.

**Comment by LeoMeinel** [comment]
https://raid.wiki.kernel.org/index.php/RAID_Boot

https://superuser.com/questions/822105/boot-partition-for-software-raid-1

**Comment by LeoMeinel** [comment]
https://wiki.archlinux.org/title/RAID

According to my interpretation of this wiki entry RAID1 would allow me to just have /boot in the RAID without any additional steps required.

**Comment by LeoMeinel** [comment]
I might have to `set root=(md/0)`

**Comment by LeoMeinel** [comment]
This error now shows up on boot, before entering any password.

![GRUB Error](https://user-images.githubusercontent.com/20671121/188237020-dbc60623-1411-48a9-bad3-dfa692d6273e.png)

**Comment by LeoMeinel** [comment]
This issue is probably caused by GRUB2 not supporting LUKS2. Therefore I am now trying https://aur.archlinux.org/packages/grub-improved-luks2-git as linked on the Archwiki

**Comment by LeoMeinel** [comment]
A big problem with having /boot on the same partition is however that I think there is no way to implement secure boot.

**Comment by LeoMeinel** [comment]
The system manages to boot and decrypt the drive now.

**Comment by LeoMeinel** [comment]
# TODO

- [ ] Prevent second prompt for passphrase
- [ ] Fix error when loading kernel

**Comment by LeoMeinel** [comment]
Error when loading kernel:

![Screenshot_archlinux_2022-09-03_13:31:03](https://user-images.githubusercontent.com/20671121/188268440-67ae28d2-7d09-43c8-86e7-9adc10433537.png)

**Comment by LeoMeinel** [comment]
https://forum.manjaro.org/t/grub-error-sparse-file-not-allowed/20267/6

**Comment by LeoMeinel** [comment]
It seems like the only solution is to disable GRUB_SAVEDEFAULT

**Comment by LeoMeinel** [comment]
# TODO

- [ ] Make /boot a seperate partition
- [ ] [cryptboot](https://github.com/kmille/cryptboot); [mkinitcpio-chkcryptoboot](https://aur.archlinux.org/packages/mkinitcpio-chkcryptoboot)

**Comment by LeoMeinel** [comment]
> # TODO
> * [ ]  Make /boot a seperate partition
> * [ ]  [cryptboot](https://github.com/kmille/cryptboot); [mkinitcpio-chkcryptoboot](https://aur.archlinux.org/packages/mkinitcpio-chkcryptoboot)

This might get pretty complicated as seen in #37

**Comment by LeoMeinel** [comment]
This is the current partition layout

![Screenshot_archlinux_2022-09-03_16:17:11](https://user-images.githubusercontent.com/20671121/188274471-6a19896a-7649-433b-8886-204c9f060d1b.png)

**Comment by LeoMeinel** [comment]
error: diskfilter writes are not supported

**Comment by LeoMeinel** [comment]
booting works now, also decrypting both drives.

**Comment by LeoMeinel** [comment]
After decrypting boot

error: diskfilter writes are not supported

After decrypting root

![Screenshot_archlinux_2022-09-03_16:59:47](https://user-images.githubusercontent.com/20671121/188276355-07ddba9b-7a9a-417c-825e-4711ebba6a9a.png)

**Comment by LeoMeinel** [comment]
If this is fixed, this setup should work!

**Comment by LeoMeinel** [comment]
Checking and editing `/etc/fstab` manually may solve this

**Comment by LeoMeinel** [comment]
> Checking and editing `/etc/fstab` manually may solve this

I should definetly find out why `/etc/fstab` gets generated incorrectly if it actually is!

**Comment by LeoMeinel** [comment]
https://wiki.archlinux.org/title/Dm-crypt/Specialties#mkinitcpio-chkcryptoboot

**Comment by LeoMeinel** [comment]
Also see https://wiki.archlinux.org/title/Unified_Extensible_Firmware_Interface/Secure_Boot

**Comment by LeoMeinel** [comment]
# TODO

- [ ] Fix boot
- [ ] [cryptboot](https://github.com/kmille/cryptboot)
- [ ] [mkinitcpio-chkcryptoboot](https://aur.archlinux.org/packages/mkinitcpio-chkcryptoboot)

**Comment by LeoMeinel** [comment]
`/etc/fstab`

![Screenshot_archlinux_2022-09-04_16:12:46](https://user-images.githubusercontent.com/20671121/188317968-99443e74-7f25-4b63-84df-543dfd7cc26a.png)

**Comment by LeoMeinel** [comment]
`/etc/default/chkcryptoboot.conf`

![Screenshot_archlinux_2022-09-04_16:30:22](https://user-images.githubusercontent.com/20671121/188318712-56c0ac60-df46-4381-b13f-3fc1ffff3000.png)

`/etc/cryptboot.conf`

![Screenshot_archlinux_2022-09-04_16:29:25](https://user-images.githubusercontent.com/20671121/188318730-9105fae3-0621-4aa1-9478-23793bc0af34.png)

**Comment by LeoMeinel** [comment]
Error: chkcryptoboot wrong EFISTUB

**Comment by LeoMeinel** [comment]
For some reason /dev/mapper/md0_crypt is not a valid LUKS device

![Screenshot_archlinux_2022-09-04_18:31:14](https://user-images.githubusercontent.com/20671121/188323652-c3f99f69-27f5-4829-94ce-5013efee85e1.png)

**Comment by LeoMeinel** [comment]
> For some reason /dev/mapper/md0_crypt is not a valid LUKS device
> 
> ![Screenshot_archlinux_2022-09-04_18:31:14](https://user-images.githubusercontent.com/20671121/188323652-c3f99f69-27f5-4829-94ce-5013efee85e1.png)

This may be just an unimportant warning but I should at least see why it pops up!

**Comment by LeoMeinel** [comment]
> > For some reason /dev/mapper/md0_crypt is not a valid LUKS device
> > ![Screenshot_archlinux_2022-09-04_18:31:14](https://user-images.githubusercontent.com/20671121/188323652-c3f99f69-27f5-4829-94ce-5013efee85e1.png)
> 
> This may be just an unimportant warning but I should at least see why it pops up!

I'm pretty sure this is because I am using LUKS2

**Comment by LeoMeinel** [comment]
First boot error (after decrypting boot):

![Screenshot_archlinux_2022-09-04_21:49:11](https://user-images.githubusercontent.com/20671121/188331058-3a181a1b-c7d8-46ea-9d22-15cf516288ee.png)

**Comment by LeoMeinel** [comment]
Maybe Not using uuids in root would be better.

This is way harder than I thought. But it's always good to learn.

**Comment by LeoMeinel** [comment]
VM now hangs after entering the correct passphrase.
There are no errors sadly.

![Screenshot_archlinux_2022-09-04_22:51:23](https://user-images.githubusercontent.com/20671121/188332983-ed55876e-10b6-4b1f-85cf-4f542dcba15f.png)

**Comment by LeoMeinel** [comment]
![Screenshot_archlinux_2022-09-03_16:17:11_cropped](https://user-images.githubusercontent.com/20671121/188334621-5ecdbb58-ad2b-4c8f-9853-1f67bd27ee14.png)

**Comment by LeoMeinel** [comment]
![Screenshot_archlinux_2022-09-04_23:48:40](https://user-images.githubusercontent.com/20671121/188334831-df15d09d-0fbf-4193-9def-881bb4f90e79.png)

**Comment by LeoMeinel** [comment]
![Uploading Screenshot_archlinux_2022-09-04_23:48:40_cropped.png…]()

**Comment by LeoMeinel** [comment]
![Screenshot_archlinux_2022-09-04_23:48:40_cropped](https://user-images.githubusercontent.com/20671121/188334882-39560315-13fa-4e45-9c6a-87973d3a46cf.png)

**Comment by LeoMeinel** [comment]
https://askubuntu.com/questions/711016/slow-boot-a-start-job-is-running-for-dev-disk-by

**Comment by LeoMeinel** [comment]
# TODO

- [x] Use UUID in /etc/crypttab
- [ ] Add noauto to /etc/crypttab
- [ ] Fix boot
- [ ] [cryptboot](https://github.com/kmille/cryptboot)

https://www.freedesktop.org/software/systemd/man/crypttab.html

**Comment by LeoMeinel** [comment]
volume-name encrypted-device key-file options

md0_crypt UUID=... none noauto

**Comment by LeoMeinel** [comment]
booting works fine now! None of the boot or efi partitions are mounted at boot and everything decrypts just fine.

Now I only have to hope that cryptboot works like I set it up.
Might be hard to actually judge because I am not sure if my VM setup is correct.

**Comment by LeoMeinel** [comment]
Seems to be working just fine
